- name: Play level Variables
  hosts: local
  connection: local
  vars:
    course: Devops with aws
    duration: 10HR
    trainer: sivakumar
  tasks:
  - name: Printing Corse Info
    vars:
      course: Ansible
    ansible.builtin.debug:
      msg: "Hello {{ course }} which is of duration {{ duration }} and is taken by trainer {{ trainer }}"
  - name: Printing Corse Info
    ansible.builtin.debug:
      msg: "Hello {{ course }} which is of duration {{ duration }} and is taken by trainer {{ trainer }}"
    
    
