- name: shell vs command
  hosts: frontend
  tasks:
  - name: Shell vs command
    ansible.builtin.shell: "ls-ltr >/tmp/output.txt"
    register: command_result

  - name: print outcome
    ansible.builtin.debug:
      msg: "Outcome of the command is {{ command_result }}"

  